version: 2
jobs:
  build:
    working_directory: ~/maiwiki
    docker:
      - image: rayriffy/composer-yarn:latest
        environment:
          DEPLOY_HOST: $DEPLOY_HOST
          DEPLOY_COMMAND: $DEPLOY_COMMAND
    steps:
      - checkout
      - run:
          name: Install required packages
          command: |
            apk add libpng-dev
      - run:
          name: Composer
          command: |
            composer install
      - run:
          name: Install Packages
          command: |
            yarn
      - run:
          name: Build script
          command: |
            yarn run prod
      - run:
          name: Migrate Database
          command: |
            php artisan migrate
      - run:
          name: Seed Database
          command: |
            php artisan db:seed
  deploy:
    machine:
        enabled: true
    working_directory: ~/maiwiki
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c7:29:52:e0:f0:33:ca:91:1b:30:3a:96:1f:34:a7:fd"
      - run:
          name: Deploy to Server
          command: |
            ssh -i ~/.ssh/id_rsa_c72952e0f033ca911b303a961f34a7fd $DEPLOY_HOST '$DEPLOY_COMMAND && composer install && php71 artisan migrate && yarn && yarn run prod'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release